---
- name: Install virtualenv package
  pip:
      name: virtualenv
      state: latest

- name: Create virtualenv directory if it doesn't exist
  file:
    path: "{{ virtualenv_dir }}/awslogs"
    state: directory
    owner: "{{ scripts_owner }}"
    group: "{{ scripts_group }}"
    mode: 0755

- name: Copy the requirements file
  copy:
    src: requirements.txt
    dest: "{{ scripts_dir }}/awslogs-requirements.txt"
    owner: "{{ scripts_owner }}"
    group: "{{ scripts_group }}"
    mode: 0755
  when: create_virtualenv

- name: Create virtualenv if create_virtualenv
  pip:
    requirements: "{{ scripts_dir }}/awslogs-requirements.txt"
    virtualenv: "{{ virtualenv_dir }}/awslogs"
  when: create_virtualenv
