---
- name: Ensure virtualenv directory exists
  file:
    path: "{{ awslogs_virtualenv_dir }}"
    state: directory
    owner: "{{ scripts_owner }}"
    group: "{{ scripts_group }}"
    mode: 0755
  register:
    virtualenv_dir

- block:
  - name: Install virtualenv package if virtualenv dir was created
    pip:
      name: virtualenv
      state: latest

  - name: Copy the requirements file if virtualenv dir was created
    copy:
      src: requirements.txt
      dest: "{{ awslogs_scripts_dir }}/awslogs-requirements.txt"
      owner: "{{ scripts_owner }}"
      group: "{{ scripts_group }}"
      mode: 0755

  - name: Install virtualenv requirements if virtualenv dir was created
    pip:
      requirements: "{{ awslogs_scripts_dir }}/awslogs-requirements.txt"
      virtualenv: "{{ awslogs_virtualenv_dir }}"

  when: virtualenv_dir | changed
