---
- name: Ensure virtualenv directory exists
  file:
    path: "{{ awslogs_virtualenv_dir }}"
    state: directory
    owner: "{{ scripts_owner }}"
    group: "{{ scripts_group }}"
    mode: 0755
  register:
    awslogs_virtualenv_dir_output

- block:
  - name: Copy the requirements file if virtualenv dir was created
    copy:
      src: requirements.txt
      dest: "{{ awslogs_scripts_dir }}/awslogs-requirements.txt"
      owner: "{{ scripts_owner }}"
      group: "{{ scripts_group }}"
      mode: 0755

  - name: Install virtualenv requirements if virtualenv dir was created
    pip:
      requirements: "{{ awslogs_scripts_dir }}/awslogs-requirements.txt"
      virtualenv: "{{ awslogs_virtualenv_dir }}"

  # Only perform the virtualenv create if the directory doesn't exist
  when: awslogs_virtualenv_dir_output | changed
